### ISSUE TITLE
Git pull rebase

### ISSUE THREAD

**Issue by Qix-** [arslanbilal/git-cheat-sheet#19]
One of the big things constantly seen in the OSS community are `merged origin/master with master` commits caused by diverged branches being pulled from a remote.

I think it would be beneficial to at least list `git pull --rebase origin master` somewhere on the cheatsheet.

**Comment by wzhishen** [comment]
You have exactly the point I want to add. `git pull --rebase` will be very useful for enabling a pull without introducing redundant merge commit so that we can keep the commit tree linear.

**Comment by arslanbilal** [comment]
I added your changes @wzhishen Thanks again!
