### ISSUE TITLE
Change proposed in "git status"

### ISSUE THREAD

**Issue by martiansideofthemoon** [arslanbilal/git-cheat-sheet#26]
Great cheat sheet! Wouldn't it be more appropriate to re-frame "Changed files in your working directory" to "Changes in working directory" or something more appropriate as the command mentions details on untracked files, deleted files as well.

**Comment by arslanbilal** [comment]
Yes, you're right! Thanks @martiansideofthemoon !!

**Comment by martiansideofthemoon** [comment]
Yeah it looks better now :smile:
