### ISSUE TITLE
Hindi cheat sheet

### ISSUE THREAD

**Issue by arslanbilal** [arslanbilal/git-cheat-sheet#35]
Here is the issue for arguing to includes on this cheat sheet. @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
#33 is the PR

**Comment by martiansideofthemoon** [comment]
@arslanbilal , more or less complete. Do have a look!

**Comment by arslanbilal** [comment]
Looks good, thank you! :+1:

**Comment by arslanbilal** [comment]
Do you think to continue to contribute on the Hindi cheat sheet? @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
@arslanbilal , yes most definitely! I've been  a bit busy. I'll continue soon :smile:

**Comment by arslanbilal** [comment]
Okay 😊👍🏼

**Comment by mecyborg** [comment]
That's really cool. I would like to pitch into this.

**Comment by martiansideofthemoon** [comment]
@mecyborg Hi! It would be good if you could complete this

**Comment by spyshiv** [comment]
@arslanbilal  Can I take this one ?? I Know Hindi very well.

**Comment by arslanbilal** [comment]
Of course, I would be very happy. @spyshiv

**Comment by syedjawadakhtar** [comment]
I see some minor markdown formatting and paraphrasing is few sentences. Can I reopen this issue?

**Comment by arslanbilal** [comment]
If you want, of course! It would be great.
