### ISSUE TITLE
Update Hindi git-sheet

### ISSUE THREAD

**Issue by syedjawadakhtar** [arslanbilal/git-cheat-sheet#73]
A few changes that are required in the `git-cheat-sheet-hi.md` are:
1. Fix missing spaces after hash characters in an atx style headings to make it readable.
2. Fix all fenced code blocks that have a blank line both before and after.
3. Replacing/Removing typos of some words like कमेट by कमिट - giving the right pronunciation to words.
4. Translation of a few commands written in English at the end of the document.
5. Add fenced code with specified language - shell.
6. Remove dollar signs before commands.
7. Added proper linking from content to headings
8. Making notes in italic using underscores instead of <em><sub> tags
9. Writing some words in a respectful manner like करो -> करें

New code segments:

1. Setup commands - सेटअप (व्यवस्था)
2. Configuration Files - कॉन्फ़िगरेशन फ़ाइलें
3. Move and Rename commands - चाल और नाम बदलें
4. Update and Publish commands - अद्यतन और प्रकाशित करें

_P.S.: I'm an Indian and I know about writing comprehensible Hindi. [yet any comments from pros are welcomed]_

**Comment by arslanbilal** [comment]
If you have time to correct the issues, please do that! Thank you for your time to contribute to the project.
