### ISSUE TITLE
Add set user name and password

### ISSUE THREAD

**Issue by m-alzahrani** [arslanbilal/git-cheat-sheet#78]
السلام عليكم ،
عمل رائع تُشكر عليه

حبيت اضيف لك
Set your username:
git config --global user.name "FIRST_NAME LAST_NAME"
Set your email address:
git config --global user.email "MY_NAME@example.com"

مهمه خاصة لما نتعامل مع VS code 
نواجه خطأ بسببها اذا مااعددناها مسبقاً

وشكراً

**Comment by arslanbilal** [comment]
Thank you 👍🏼 People will look up this issue when encountering a VSCode git problem.
